### ISSUE TITLE
parameters to produce the klipper.bin

### ISSUE THREAD

**Issue by boudreau** [aidancrowther/Anycubic-Predator-Klipper-Configuration#1]
Hi,

any chance that you can post the parameters you used to create the firmware klipper.bin file from the "make menuconfig" ?

This will be useful in the future when upgrading.

Thanks

**Comment by boudreau** [comment]
I think you could post the ".config" after the "make menuconfig", it should contain all the info needed for the make of the firmware.

**Comment by aidancrowther** [comment]
Sorry for missing this, I don't believe I have the config I used handy but I will take a look

**Comment by aidancrowther** [comment]
I've included the .config file in the repo
